services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cinephix-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - cinephix-network

networks:
  cinephix-network:
    external: true